package com.practices.ai.agent;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.ai.ollama.api.OllamaChatOptions;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;

import com.practices.ai.agent.dto.AgentExecutionResponse;
import com.practices.ai.config.AiProperties;
import com.practices.ai.agent.dto.AgentPlan;
import com.practices.ai.agent.dto.AgentPlanResponse;
import com.practices.ai.agent.dto.ProposedChange;
import com.practices.ai.memory.ChatMessage;
import com.practices.ai.memory.ChatMessage.Role;
import com.practices.ai.memory.ConversationMemory;
import com.practices.entity.Employee;
import com.practices.repository.EmployeeRepo;
import com.practices.service.EmployeeService;

/**
 * Explicit Reason -&gt; Plan -&gt; Execute -&gt; Summarize agent for bulk/single employee actions.
 *
 * <p>This is the "Employee AI Agent" - distinct from both {@link com.practices.ai.tools.EmployeeCrudTools}
 * (single-shot Spring AI function calling, model-driven tool loop) and the LangChain4j agent under
 * {@code com.practices.ai.langchain4j.agent} (a chat-oriented AI Service). This agent keeps the model out
 * of the actual database writes entirely: the model only ever produces a structured {@link AgentPlan}
 * (Reason). Matching employees and computing before/after values (Plan) is deterministic Java code.
 * Nothing is written until a caller explicitly confirms (Execute), and the final report (Summarize) is
 * built from the real applied changes, not generated by the model.</p>
 */
@Service
public class EmployeeAgentService {
    private static final Logger log = LoggerFactory.getLogger(EmployeeAgentService.class);
    private static final Duration PLAN_TTL = Duration.ofMinutes(15);

    private final ChatClient chatClient;
    private final Resource planPrompt;
    private final EmployeeRepo employeeRepo;
    private final EmployeeService employeeService;
    private final ConversationMemory memory;
    private final AiProperties aiProperties;
    private final Map<String, PendingPlan> pendingPlans = new ConcurrentHashMap<>();

    public EmployeeAgentService(
            ChatClient chatClient,
            @Value("classpath:/prompts/employee-agent-plan.st") Resource planPrompt,
            EmployeeRepo employeeRepo,
            EmployeeService employeeService,
            ConversationMemory memory,
            AiProperties aiProperties) {
        this.chatClient = chatClient;
        this.planPrompt = planPrompt;
        this.employeeRepo = employeeRepo;
        this.employeeService = employeeService;
        this.memory = memory;
        this.aiProperties = aiProperties;
    }

    public AgentPlanResponse plan(String conversationId, String instruction) {
        evictExpiredPlans();
        log.info("[AGENT][REASON] conversationId={} instruction=\"{}\"", conversationId, instruction);

        Instant now = Instant.now();
        memory.append(conversationId, new ChatMessage(Role.USER, instruction, now));

        String rendered = new PromptTemplate(planPrompt).render(Map.of(
                "history", formatHistory(memory.get(conversationId)),
                "instruction", instruction));

        AgentPlan agentPlan = chatClient.prompt()
                .user(rendered)
                .options(OllamaChatOptions.builder().model(aiProperties.defaultModel()).enableThinking())
                .call()
                .entity(AgentPlan.class);

        log.info("[AGENT][PLAN] conversationId={} reasoning=\"{}\" filter={} action={} clarification={}",
                conversationId, agentPlan.reasoning(), agentPlan.filter(), agentPlan.action(),
                agentPlan.clarificationNeeded());

        if (agentPlan.clarificationNeeded() != null && !agentPlan.clarificationNeeded().isBlank()) {
            memory.append(conversationId, new ChatMessage(Role.ASSISTANT, agentPlan.clarificationNeeded(), now));
            return new AgentPlanResponse(
                    conversationId, null, agentPlan.reasoning(), agentPlan.clarificationNeeded(), List.of(), false, now);
        }

        List<Employee> matches = employeeRepo.findAll().stream()
                .filter(employee -> matchesFilter(employee, agentPlan.filter()))
                .toList();

        List<ProposedChange> changes = matches.stream()
                .map(employee -> proposeChange(employee, agentPlan.action()))
                .filter(Objects::nonNull)
                .toList();

        if (changes.isEmpty()) {
            String message = "No employees matched that request, so there is nothing to change.";
            memory.append(conversationId, new ChatMessage(Role.ASSISTANT, message, now));
            return new AgentPlanResponse(conversationId, null, agentPlan.reasoning(), message, List.of(), false, now);
        }

        String planId = UUID.randomUUID().toString();
        pendingPlans.put(planId, new PendingPlan(
                conversationId, agentPlan.action(), matches.stream().map(Employee::getId).toList(), now));

        String preview = renderPlanPreview(changes);
        memory.append(conversationId, new ChatMessage(Role.ASSISTANT, preview, now));

        log.info("[AGENT][PLAN] conversationId={} planId={} matchedCount={}", conversationId, planId, changes.size());

        return new AgentPlanResponse(conversationId, planId, agentPlan.reasoning(), null, changes, true, now);
    }

    public AgentExecutionResponse confirm(String conversationId, String planId, boolean confirm) {
        PendingPlan pending = pendingPlans.get(planId);
        if (pending == null || !pending.conversationId().equals(conversationId)) {
            throw new IllegalArgumentException("No pending plan found for this conversation. Ask again to create a new plan.");
        }
        pendingPlans.remove(planId);
        Instant now = Instant.now();

        if (!confirm) {
            log.info("[AGENT][EXECUTE] conversationId={} planId={} cancelled by caller", conversationId, planId);
            String message = "Cancelled - no changes were made.";
            memory.append(conversationId, new ChatMessage(Role.ASSISTANT, message, now));
            return new AgentExecutionResponse(conversationId, planId, false, message, List.of(), now);
        }

        List<ProposedChange> applied = new ArrayList<>();
        for (Long employeeId : pending.employeeIds()) {
            employeeRepo.findById(employeeId).ifPresent(employee -> {
                ProposedChange change = proposeChange(employee, pending.action());
                if (change == null) {
                    return;
                }
                applyAction(employee, pending.action());
                employeeService.updateEmployee(employeeId, employee);
                applied.add(change);
                log.info("[AGENT][EXECUTE] conversationId={} employeeId={} field={} before={} after={}",
                        conversationId, employeeId, change.field(), change.beforeValue(), change.afterValue());
            });
        }

        String summary = renderExecutionSummary(applied);
        log.info("[AGENT][SUMMARIZE] conversationId={} planId={} appliedCount={}", conversationId, planId, applied.size());
        memory.append(conversationId, new ChatMessage(Role.ASSISTANT, summary, now));

        return new AgentExecutionResponse(conversationId, planId, true, summary, applied, now);
    }

    private boolean matchesFilter(Employee employee, AgentPlan.Filter filter) {
        if (filter == null) {
            return true;
        }
        if (isSet(filter.department()) && !contains(employee.getDepartment(), filter.department())) {
            return false;
        }
        if (isSet(filter.role()) && !contains(employee.getRole(), filter.role())) {
            return false;
        }
        if (isSet(filter.performance()) && !contains(employee.getPerformance(), filter.performance())) {
            return false;
        }
        if (isSet(filter.nameContains()) && !contains(employee.getName(), filter.nameContains())) {
            return false;
        }
        if (filter.minSalary() != null && (employee.getSalary() == null || employee.getSalary() < filter.minSalary())) {
            return false;
        }
        if (filter.maxSalary() != null && (employee.getSalary() == null || employee.getSalary() > filter.maxSalary())) {
            return false;
        }
        return true;
    }

    private ProposedChange proposeChange(Employee employee, AgentPlan.Action action) {
        if (action == null || action.type() == null) {
            return null;
        }
        return switch (action.type()) {
            case "increase_salary_percent" -> {
                if (employee.getSalary() == null || action.amount() == null) yield null;
                double after = employee.getSalary() * (1 + action.amount() / 100.0);
                yield new ProposedChange(employee.getId(), employee.getName(), "salary",
                        String.valueOf(employee.getSalary()), String.valueOf(round2(after)));
            }
            case "increase_salary_flat" -> {
                if (employee.getSalary() == null || action.amount() == null) yield null;
                double after = employee.getSalary() + action.amount();
                yield new ProposedChange(employee.getId(), employee.getName(), "salary",
                        String.valueOf(employee.getSalary()), String.valueOf(round2(after)));
            }
            case "set_salary" -> {
                if (action.amount() == null) yield null;
                yield new ProposedChange(employee.getId(), employee.getName(), "salary",
                        String.valueOf(employee.getSalary()), String.valueOf(round2(action.amount())));
            }
            case "set_performance" -> {
                if (action.textValue() == null) yield null;
                yield new ProposedChange(employee.getId(), employee.getName(), "performance",
                        String.valueOf(employee.getPerformance()), action.textValue());
            }
            case "set_role" -> {
                if (action.textValue() == null) yield null;
                yield new ProposedChange(employee.getId(), employee.getName(), "role",
                        String.valueOf(employee.getRole()), action.textValue());
            }
            default -> null;
        };
    }

    private void applyAction(Employee employee, AgentPlan.Action action) {
        switch (action.type()) {
            case "increase_salary_percent" -> employee.setSalary(round2(employee.getSalary() * (1 + action.amount() / 100.0)));
            case "increase_salary_flat" -> employee.setSalary(round2(employee.getSalary() + action.amount()));
            case "set_salary" -> employee.setSalary(round2(action.amount()));
            case "set_performance" -> employee.setPerformance(action.textValue());
            case "set_role" -> employee.setRole(action.textValue());
            default -> throw new IllegalStateException("Unsupported action type: " + action.type());
        }
    }

    private String renderPlanPreview(List<ProposedChange> changes) {
        StringBuilder sb = new StringBuilder("Found ")
                .append(changes.size())
                .append(changes.size() == 1 ? " matching employee:\n" : " matching employees:\n");
        int index = 1;
        for (ProposedChange change : changes) {
            sb.append(index++).append(". ").append(change.name())
                    .append(" - ").append(change.field()).append(" ")
                    .append(change.beforeValue()).append(" to ").append(change.afterValue()).append("\n");
        }
        sb.append("Reply confirm to apply these changes, or cancel to discard them.");
        return sb.toString();
    }

    private String renderExecutionSummary(List<ProposedChange> applied) {
        if (applied.isEmpty()) {
            return "No changes were applied.";
        }
        StringBuilder sb = new StringBuilder("Updated ")
                .append(applied.size())
                .append(applied.size() == 1 ? " employee:\n" : " employees:\n");
        int index = 1;
        for (ProposedChange change : applied) {
            sb.append(index++).append(". ").append(change.name())
                    .append(" - ").append(change.field()).append(" ")
                    .append(change.beforeValue()).append(" to ").append(change.afterValue()).append("\n");
        }
        return sb.toString();
    }

    private void evictExpiredPlans() {
        Instant cutoff = Instant.now().minus(PLAN_TTL);
        pendingPlans.entrySet().removeIf(entry -> entry.getValue().createdAt().isBefore(cutoff));
    }

    private boolean isSet(String value) {
        return value != null && !value.isBlank();
    }

    private boolean contains(String value, String needle) {
        return value != null && value.toLowerCase(Locale.ROOT).contains(needle.toLowerCase(Locale.ROOT));
    }

    private double round2(double value) {
        return Math.round(value * 100.0) / 100.0;
    }

    private String formatHistory(List<ChatMessage> history) {
        if (history.isEmpty()) {
            return "No previous conversation.";
        }
        return history.stream()
                .map(item -> item.role().name() + ": " + item.content())
                .reduce((left, right) -> left + "\n" + right)
                .orElse("No previous conversation.");
    }

    private record PendingPlan(String conversationId, AgentPlan.Action action, List<Long> employeeIds, Instant createdAt) {
    }
}
